/*
// Created by ahmad on 7/29/19.
/*/

#ifndef PRE_COURSE_1_C_AHMADAMARA_BOOKS_CONSTANTS_H
#define PRE_COURSE_1_C_AHMADAMARA_BOOKS_CONSTANTS_H

#define MAX_BOOK_NAME_LEN 50

#endif /*PRE_COURSE_1_C_AHMADAMARA_BOOKS_CONSTANTS_H*/
